name: Sanitizers
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: sudo apt-get install -y gcc cmake
      - name: Build debug_threads
        run: make MODE=debug_threads
      - name: Clean
        run: make clean
      - name: Build debug
        run: make MODE=debug
      - name: Run
        run: ./program -f cloud_points/cloud_point_test.laz -t